### ISSUE TITLE
[Regression] Reflex build fails on Python 3.14 due to Pydantic v1 incompatibility (introduced in PR #5891)

### ISSUE THREAD

**Issue by ParagGhatage** [reflex-dev/reflex#5964]
## Description

After the recent merge of [[#5891 ]](https://github.com/reflex-dev/reflex/pull/5891) (merged ~3 weeks ago), Reflex builds are failing on **Python 3.14**.

The issue appears to stem from **Pydantic v1’s incompatibility** with Python 3.14’s updated typing internals.
Since Reflex still imports from `pydantic.v1`, the build breaks during editable installation or runtime imports.

---

## Steps to Reproduce

```bash
# Clean environment
uv sync
```

---

## Observed Behavior

```
UserWarning: Core Pydantic V1 functionality isn't compatible with Python 3.14 or greater.
TypeError: _eval_type() got an unexpected keyword argument 'prefer_fwd_module'
```

**Stack Trace (trimmed):**

```
TypeError: _eval_type() got an unexpected keyword argument 'prefer_fwd_module'
Unable to evaluate type annotation 'ClassVar[MetaData]'
subprocess.CalledProcessError: Command '['python', '-m', 'reflex.utils.pyi_generator']' returned non-zero exit status 1
```

---

## Expected Behavior

Reflex should build and sync cleanly (as it does on Python 3.11–3.13).

---

## Root Cause Analysis

* Python 3.14 introduced breaking changes in `typing` and `_eval_type()`.
* `pydantic.v1` (used in Reflex base models and SQLModel) depends on old internal APIs.
* This causes Reflex builds to fail when Pydantic tries to evaluate model type hints.

---

## Suggested Fix

Until Reflex migrates fully to **Pydantic v2**, temporarily:

###  Pin Python version in `pyproject.toml`

```toml
[project]
requires-python = ">=3.9,<3.14"
```

`.python-version ` file as (instead of current 3.14)
```.python-version

3.13
```

## Environment

* **Python:** 3.14.0b1
* **OS:** Arch Linux
* **Package Manager:** uv (latest)
* **Reflex branch:** `main`
* **Error introduced by:** [[#5891 ](https://github.com/reflex-dev/reflex/pull/5891)](https://github.com/reflex-dev/reflex/pull/5891)

---

## Additional Notes

Downgrading to **Python 3.13** resolves the issue completely.

This affects users building Reflex locally or via `uv sync` with Python 3.14 as the default interpreter.

CC: @adhami3310 
 - this regression seems to have appeared after your recent PR.

<img width="1493" height="967" alt="Image" src="https://github.com/user-attachments/assets/42b83b5f-b7a6-4541-9672-7342e91c9d82" />

**Comment by masenf** [comment]
Unable to reproduce 

```
docker run -it python:3.14 /bin/bash
pip install uv
cd /root
git clone https://github.com/reflex-dev/reflex
mkdir my-app
cd my-app
uv init
uv add --editable /root/reflex
uv run reflex init --template blank
uv run reflex run
```

No errors are seen, works fine and is editable.

Maybe you have some older version in your local checkout?

**Comment by ParagGhatage** [comment]
> Unable to reproduce
> 
> ```
> docker run -it python:3.14 /bin/bash
> pip install uv
> cd /root
> git clone https://github.com/reflex-dev/reflex
> mkdir my-app
> cd my-app
> uv init
> uv add --editable /root/reflex
> uv run reflex init --template blank
> uv run reflex run
> ```
> 
> No errors are seen, works fine and is editable.
> 
> Maybe you have some older version in your local checkout?

Try running  `uv sync` in the cloned Reflex repo root, according to steps in the CONTRIBUTING.md(https://github.com/reflex-dev/reflex/blob/main/CONTRIBUTING.md)
