### ISSUE TITLE
Backend-only vars no longer mutable

### ISSUE THREAD

**Issue by MShekow** [reflex-dev/reflex#5829]
**Describe the bug**
In Reflex 0.7.x, I was able to define a **backend-only** variable such as `_list_1: rx.Field[list[int]] = rx.field([1])` and then call methods such as `self._list_1.clear()` or `self._list_1.append(2)`. This no longer works in 0.8.12.

**To Reproduce**

```python
import reflex as rx

class State(rx.State):
    """The app state."""
    _list_1: rx.Field[list[int]] = rx.field([1])

    def do_something(self):
        self._list_1.append(1)
        print("success")


def index() -> rx.Component:
    return rx.container(
        rx.button("do something", on_click=State.do_something),
        spacing="5",
        justify="center",
        min_height="85vh",
    )


app = rx.App()
app.add_page(index)
```

Shown error: **AttributeError: 'Field' object has no attribute 'append'**

**Expected behavior**
It should just work (like it does for normal State variables that are not prepended with `_`.

**Specifics (please complete the following information):**

- Python Version: 3.12.3
- Reflex Version: 0.8.12
- OS: Linux

**Comment by benedikt-bartscher** [comment]
duplicate of https://github.com/reflex-dev/reflex/issues/5629
