### ISSUE TITLE
[REF-3266] AttributeError: 'ModelPrivateAttr' object has no attribute 'update'

### ISSUE THREAD

**Issue by masenf** [reflex-dev/reflex#3642]
**Describe the bug**
With `reflex==0.5.6` and `pydantic==1.10.15`, trying to `reflex init` a new project gives an error:

```
Traceback (most recent call last):
  File "/Users/masenf/code/reflex-dev/repro-pydantic-model-private-attr/VENV/bin/reflex", line 5, in <module>
    from reflex.reflex import cli
  File "/Users/masenf/code/reflex-dev/repro-pydantic-model-private-attr/VENV/lib/python3.12/site-packages/reflex/reflex.py", line 18, in <module>
    from reflex.custom_components.custom_components import custom_components_cli
  File "/Users/masenf/code/reflex-dev/repro-pydantic-model-private-attr/VENV/lib/python3.12/site-packages/reflex/custom_components/custom_components.py", line 24, in <module>
    config = get_config()
             ^^^^^^^^^^^^
  File "/Users/masenf/code/reflex-dev/repro-pydantic-model-private-attr/VENV/lib/python3.12/site-packages/reflex/config.py", line 374, in get_config
    rxconfig = importlib.import_module(constants.Config.MODULE)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/masenf/code/reflex-dev/repro-pydantic-model-private-attr/rxconfig.py", line 3, in <module>
    config = rx.Config(
             ^^^^^^^^^^
  File "/Users/masenf/code/reflex-dev/repro-pydantic-model-private-attr/VENV/lib/python3.12/site-packages/reflex/config.py", line 248, in __init__
    self._non_default_attributes.update(kwargs)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ModelPrivateAttr' object has no attribute 'update'
```

**To Reproduce**

In a fresh virtualenv

```console
pip install reflex==0.5.6
pip install pydantic==1.10.15
reflex init
```

**Expected behavior**
It prompts to create a new project.

**Specifics (please complete the following information):**
 - Python Version: 3.12
 - Reflex Version: 0.5.6
 - OS: macOS 14

**Additional context**
Downgrade to reflex 0.5.5 or upgrade to pydantic 1.15.16 and the issue goes away.

<sub>[REF-3266](https://linear.app/reflex-dev/issue/REF-3266/attributeerror-modelprivateattr-object-has-no-attribute-update)</sub>

**Comment by masenf** [comment]
Introduced in #3610, which changed the import order for this `reflex.utils.compat` module
